add_newline = false

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ](bold red) "
format = "[{](bold #ffd08e)[ H ](bold #ff9001)[}](bold #ffd08e) $symbol "

[directory]
truncation_length = 3
truncation_symbol = "../"
read_only = " ï ½"

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡ ${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[status]
symbol = "ğŸ’£ "
format = '[\[$symbol$status\]]($style) '
disabled = false

[aws]
symbol = "îŒ½  "

[battery]
full_symbol = "ï•¸ "
charging_symbol = "ï–ƒ "
discharging_symbol = "ï–‚ "

[conda]
symbol = "ï„Œ  "

[dart]
symbol = "î˜  "

[docker]
symbol = "ïŒˆ  "

[elixir]
symbol = "î‰µ  "

[elm]
symbol = "î˜¬  "

[git_branch]
symbol = "ï˜  "

[golang]
symbol = "î˜§  "

[haskell]
symbol = "î˜Ÿ  "

[hg_branch]
symbol = "ï˜  "

[java]
symbol = "î‰–  "

[julia]
symbol = "î˜¤  "

[memory_usage]
symbol = "ï¡š  "

[nim]
symbol = "ïš¤  "

[nix_shell]
symbol = "ï‹œ  "

[nodejs]
symbol = "î‰  "

[package]
symbol = "ï£–  "

[perl]
symbol = "î©  "

[php]
symbol = "î˜ˆ  "

[python]
symbol = "î˜†  "

[ruby]
symbol = "îˆ¾  "

[rust]
symbol = "î¨  "

[swift]
symbol = "ï¯£  "

